//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruckSimulatorDAL_n
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoutePoint : Point
    {
        public int VehicleId { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
